In [3]:
#3. import numpy as np

import numpy as np

In [26]:
#4. 3x3 matrix range 0 to 8. define matrix as a


a = array ([[0,1,2],[3,4,5],[6,7,8]])
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
#5. what is the output

print (sum(range (5),-1))
from numpy import *
print (sum(range (5),-1))

10
10


In [19]:
#6. is the expression is true

np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\User\Anaconda2\lib\site-packages\ipykernel\__main__.py:3: RuntimeWarning: invalid value encountered in sqrt
  app.launch_new_instance()


False

In [40]:
#7. vector value of size 30 and find the mean value

a = random.rand(30)
a

meana = mean(a)
meana

0.39359855955537343

In [31]:
#8/9. (5x3) matrix x (3x2) matrix

c = ones([5,3])
d = ones([3,2])

cd = matmul(c,d)
cd

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])

In [32]:
ones([5,3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [33]:
ones([3,2])


array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [42]:
#10. random vector size 10 and sort it

a = random.rand(10)

sort(a)

array([ 0.0757643 ,  0.09172232,  0.1415178 ,  0.30038585,  0.3582293 ,
        0.40882516,  0.43110495,  0.61715088,  0.62837675,  0.8832756 ])

In [44]:
#11. random size 100 and replace the maximum value by 0

a = random.rand(100)

a[where (a == a.max())] = 0

In [46]:
#12. how to get diagonal of a dot product

c = arange(15).reshape(5, 3)
d = arange(9).reshape(3, 3)
diag(dot(dot(c, d), c.T))

array([  60,  672, 1932, 3840, 6396])